from .base_url_crowler import BaseJSONUrlCrowler, BaseHTMLUrlCrowler
from .html_crowlers import (
    AvitoCrowler,
    CareerspaceCrowler,
    ChangellengeCrowler,
    MtsCrowler,
    SberDevCrowler,
    VsetiCrowler,
    AichCrowler,
    ChoiciCrowler,
    RemocateCrowler,
    SuperJobCrowler,
    TwoGisDEVCrowler,
    TwoGisDEVOPSCrowler,
    TwoGisPROJECTCrowler,
    TwoGisANCrowler,
    TwoGisLEADCrowler,
    CrocCrowler,
)
from .json_crowlers import (
    HhCrowler,
    ITFutCrowler,
    OzonCrowler,
    SberCrowler,
    YandexCrowler,
    HabrCrowler,
    KasperskyCrowler,
    GazpromCrowler,
    AlfaCrowler,
)
