REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0

REDIS_DATABASE_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'

FILE_NAME = 'result.xlsx'
BOT_TOKEN = '7405045997:AAG5c0acQn62ypW6xOgeg6bNCZwCF-8cX5I'

WITH_DELETE = False
