REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 0

REDIS_DATABASE_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'

FILE_NAME = 'result.xlsx'
BOT_TOKEN = '7357401151:AAGz3IHeF1QYen2e37ZvQiMT2YpE9RhVdgQ'

DELETE_ALL = True
INCLUDE_PREVIOUS = False
