from .hh_crowler import HhCrowler
from .itfut_crowler import ITFutCrowler
from .ozon_crowler import OzonCrowler
from .sber_crowler import SberCrowler
from .yandex_crowler import YandexCrowler
from .habr_crowler import HabrCrowler
from .kaspersky_crowler import KasperskyCrowler
from .gasprom_crowler import GazpromCrowler
from .alfa_crowler import AlfaCrowler
from .domrf_crowler import DomrfCrowler
from .rosatom_crowler import RosatomCrowler
