from .hh_parser import HhParser
from .itfut_parser import ItFutParser
from .ozon_parser import OzonParser
from .sber_parser import SberParser
from .yandex_parser import YandexParser
from .habr_parser import HabrParser
from .kaspersky_parser import KasperskyParser
from .gazprom_parser import GazpromParser
from .alfa_parser import AlfaParser
