job_titles = (
    'разработчик',
    'devops',
    'backend',
    'full-stack',
    'fullstack',
    'full stack',
    'фулстак',
    'фул-стак',
    'фул стак',
    'frontend',
    'developer',
    'product manager',
    'project manager',
    'bizdev',
    'менеджер продукта',
    'менеджер проекта',
    'machine learning',
    'nlp',
    'data scientist',
    'ml engineer',
    'разработчик ml',
    'ml developer',
    'продуктовый аналитик',
    'системный аналитик',
    'аналитик данных',
    'бизнес аналитик',
    'analyst',
    'product analyst',
    'system analyst',
    'data analyst',
    'business analyst',
    'аналитик bi',
    'bi analyst',
    'teamlead',
    'руководитель',
    'тимлид',
    'тим-лид',
    'фронтенд',
    'фронт енд',
    'фронт-енд',
    'бэкенд',
    'бэк енд',
    'бэк-енд',
    'front-end',
    'back-end',
    'team-lead',
    'team lead',
    'техлид',
    'тех лид',
    'программист',
    'тестировщик',
    'системный администратор',
)

banned_job_titles = (
    'велокурьер',
    'курьер',
)
