job_titles = (
    'разработчик',
    'devops',
    'backend',
    'full-stack',
    'frontend',
    'developer',
    'product manager',
    'project manager',
    'bizdev',
    'менеджер продукта',
    'менеджер проекта',
    'machine learning',
    'nlp',
    'data scientist',
    'ml engineer',
    'разработчик ml',
    'ml developer',
    'аналитик',
    'продуктовый аналитик',
    'системный аналитик',
    'аналитик данных',
    'бизнес аналитик',
    'analyst',
    'product analyst',
    'system analyst',
    'data analyst',
    'business analyst',
    'аналитик bi',
    'bi analyst',
    'teamlead',
    'ведущий',
    'старший',
    'senior',
    'руководитель',
)
