skills_dict = {
    'back-end': 'Разработка/Backend, Разработка/Backend',
    'backend': 'Разработка/Backend, Разработка/Backend',
    'python': 'Разработка/Backend, Разработка/Fullstack, ML/DS',
    'c++': 'Разработка/Backend',
    'java': 'Разработка/Backend, Разработка/Fullstack',
    'golang': 'Разработка/Backend',
    'go': 'Разработка/Backend',
    'javascript': 'Разработка/Backend, Разработка/Frontend',
    'c#': 'Разработка/Backend',
    'c': 'Разработка/Backend',
    'ruby': 'Разработка/Backend',
    'rust': 'Разработка/Backend',
    'django': 'Разработка/Backend',
    'drf': 'Разработка/Backend',
    'rest': 'Разработка/Backend, Аналитика/Системная аналитика',
    'api': 'Разработка/Backend, Аналитика/Системная аналитика',
    'fastapi': 'Разработка/Backend',
    'flask': 'Разработка/Backend',
    'php': 'Разработка/Backend',
    'redis': 'Разработка/Backend',
    'celery': 'Разработка/Backend',
    'docker': 'Разработка/Backend, Разработка/DevOps',
    'front-end': 'Разработка/Frontend, Разработка/Frontend',
    'frontend': 'Разработка/Frontend, Разработка/Frontend',
    'react': 'Разработка/Frontend',
    'vue': 'Разработка/Frontend',
    'typescript': 'Разработка/Frontend',
    'angular': 'Разработка/Frontend',
    'html': 'Разработка/Frontend',
    'css': 'Разработка/Frontend',
    'html5': 'Разработка/Frontend',
    'css3': 'Разработка/Frontend',
    'fullstack': 'Разработка/Fullstack, Разработка/Fullstack',
    'full-stack': 'Разработка/Fullstack, Разработка/Fullstack',
    'node.js': 'Разработка/Fullstack',
    'devops': 'Разработка/DevOps, Разработка/DevOps',
    'dev-ops': 'Разработка/DevOps, Разработка/DevOps',
    'kubernetes': 'Разработка/DevOps',
    'ansible': 'Разработка/DevOps',
    'terraform': 'Разработка/DevOps',
    'jenkins': 'Разработка/DevOps',
    'git': 'Разработка/DevOps, Разработка/Backend',
    'github': 'Разработка/DevOps, Разработка/Backend',
    'gitlab': 'Разработка/DevOps, Разработка/Backend',
    'azure': 'Разработка/DevOps',
    'аналитика': 'Аналитика/Продуктовая аналитика, Аналитика/Бизнес-аналитика, Аналитика/Системная аналитика',
    'sql': 'Аналитика/Продуктовая аналитика, Аналитика/Бизнес-аналитика, Аналитика/Системная аналитика, ML/DS',
    'excel': 'Аналитика/Продуктовая аналитика',
    'r': 'Аналитика/Продуктовая аналитика',
    'power bi': 'Аналитика/Продуктовая аналитика',
    'bi': 'Аналитика/Продуктовая аналитика, Аналитика/Бизнес-аналитика',
    'tableau': 'Аналитика/Продуктовая аналитика',
    'google analytics': 'Аналитика/Продуктовая аналитика',
    'a/b': 'Аналитика/Продуктовая аналитика',
    'bpmn': 'Аналитика/Бизнес-аналитика, Аналитика/Системная аналитика',
    'uml': 'Аналитика/Бизнес-аналитика, Аналитика/Системная аналитика',
    'jira': 'Аналитика/Бизнес-аналитика, Аналитика/Системная аналитика',
    'confluence': 'Аналитика/Бизнес-аналитика, Аналитика/Системная аналитика',
    'crm': 'Аналитика/Бизнес-аналитика',
    'xml': 'Аналитика/Системная аналитика',
    'json': 'Аналитика/Системная аналитика',
    'soap': 'Аналитика/Системная аналитика',
    'pandas': 'ML/DS',
    'numpy': 'ML/DS',
    'scipy': 'ML/DS',
    'scikit-learn': 'ML/DS',
    'tensorflow': 'ML/DS',
    'pytorch': 'ML/DS',
    'hadoop': 'ML/DS',
    'spark': 'ML/DS',
    'seaborn': 'ML/DS',
    'nlp': 'ML/DS',
    'cv': 'ML/DS',
    'dl': 'ML/DS',
    'product': 'Product Management/',
    'product management': 'Project  Management/',
    'project': 'Project  Management/',
    'project management': 'Project  Management/',
    'руководитель': 'Project  Management/ , Project  Management/ , Project  Management/',
}
