skills_dict = {
    'back-end': 'Разработка/Backend, Разработка/Backend',
    'backend': 'Разработка/Backend, Разработка/Backend',
    'python': 'Разработка/Backend, Разработка/Fullstack, ML/DS, Аналитика/Дата аналитика',
    'c++': 'Разработка/Backend',
    'java': 'Разработка/Backend, Разработка/Fullstack',
    'golang': 'Разработка/Backend',
    'go': 'Разработка/Backend',
    'javascript': 'Разработка/Backend, Разработка/Frontend',
    'c#': 'Разработка/Backend',
    'c': 'Разработка/Backend',
    'ruby': 'Разработка/Backend',
    'rust': 'Разработка/Backend',
    'django': 'Разработка/Backend',
    'drf': 'Разработка/Backend',
    'rest': 'Разработка/Backend, Аналитика/Системная аналитика',
    'api': 'Разработка/Backend, Аналитика/Системная аналитика',
    'fastapi': 'Разработка/Backend',
    'flask': 'Разработка/Backend',
    'php': 'Разработка/Backend',
    'redis': 'Разработка/Backend',
    'celery': 'Разработка/Backend',
    'spring-framework': 'Разработка/Backend',
    'spring': 'Разработка/Backend',
    'spring-boot': 'Разработка/Backend',
    'airflow': 'Разработка/Backend',
    'mlflow-docker': 'Разработка/Backend',
    'bitbucket': 'Разработка/Backend',
    'spring-jpa': 'Разработка/Backend',
    'sonatype': 'Разработка/Backend, Разработка/DevOps',
    'nexus': 'Разработка/Backend, Разработка/DevOps',
    'sonarqube': 'Разработка/Backend, Разработка/DevOps',
    'teamcity': 'Разработка/Backend, Разработка/DevOps',
    'mstfs': 'Разработка/Backend, Разработка/DevOps',
    'haproxy': 'Разработка/Backend, Разработка/DevOps',
    'scoml': 'Разработка/Backend',
    'scom': 'Разработка/DevOps',
    'postgresql': 'Разработка/Backend',
    'postgres': 'Разработка/Backend',
    'pl/sql': 'Разработка/Backend',
    'clickhouse': 'Разработка/Backend',
    'vertica': 'Разработка/Backend',
    't-sql': 'Разработка/Backend',
    'maven': 'Разработка/Backend',
    'swaggerr': 'Разработка/Backend',
    'nginx': 'Разработка/Backend, Разработка/DevOps',
    'apache': 'Разработка/Backend',
    'docker': 'Разработка/Backend, Разработка/DevOps',
    'front-end': 'Разработка/Frontend, Разработка/Frontend',
    'frontend': 'Разработка/Frontend, Разработка/Frontend',
    'react': 'Разработка/Frontend',
    'vue': 'Разработка/Frontend',
    'typescript': 'Разработка/Frontend',
    'angular': 'Разработка/Frontend',
    'html': 'Разработка/Frontend',
    'css': 'Разработка/Frontend',
    'html5': 'Разработка/Frontend',
    'css3': 'Разработка/Frontend',
    'fullstack': 'Разработка/Fullstack, Разработка/Fullstack',
    'full-stack': 'Разработка/Fullstack, Разработка/Fullstack',
    'node.js': 'Разработка/Fullstack',
    'devops': 'Разработка/DevOps, Разработка/DevOps, Разработка/Backend',
    'dev-ops': 'Разработка/DevOps, Разработка/DevOps',
    'kubernetes': 'Разработка/DevOps, Разработка/Backend',
    'ansible': 'Разработка/DevOps, Разработка/Backend',
    'terraform': 'Разработка/DevOps',
    'bash': 'Разработка/DevOps, Разработка/Backend',
    'kafka': 'Разработка/DevOps, Разработка/Backend',
    'jenkins': 'Разработка/DevOps, Разработка/Backend',
    'git': 'Разработка/DevOps, Разработка/Backend',
    'github': 'Разработка/DevOps, Разработка/Backend',
    'gitlab': 'Разработка/DevOps, Разработка/Backend',
    'gitflow': 'Разработка/DevOps, Разработка/Backend',
    'azure': 'Разработка/DevOps, Разработка/Backend',
    'аналитика': 'Аналитика/Продуктовая аналитика, Аналитика/Бизнес-аналитика, Аналитика/Системная аналитика',
    'sql': 'Аналитика/Продуктовая аналитика, Аналитика/Бизнес-аналитика, Аналитика/Системная аналитика, ML/DS, Разработка/Backend',
    'excel': 'Аналитика/Продуктовая аналитика',
    'r': 'Аналитика/Продуктовая аналитика',
    'power-bi': 'Аналитика/Продуктовая аналитика, Аналитика/Дата аналитика',
    'bi': 'Аналитика/Продуктовая аналитика, Аналитика/Бизнес-аналитика, Аналитика/Дата аналитика',
    'tableau': 'Аналитика/Продуктовая аналитика',
    'google-analytics': 'Аналитика/Продуктовая аналитика',
    'a/b': 'Аналитика/Продуктовая аналитика, Аналитика/Дата аналитика',
    'bpmn': 'Аналитика/Бизнес-аналитика, Аналитика/Системная аналитика, Аналитика/Дата аналитика',
    'uml': 'Аналитика/Бизнес-аналитика, Аналитика/Системная аналитика, Аналитика/Дата аналитика',
    'jira': 'Аналитика/Бизнес-аналитика, Аналитика/Системная аналитика',
    'confluence': 'Аналитика/Бизнес-аналитика, Аналитика/Системная аналитика, Аналитика/Дата аналитика',
    'crm': 'Аналитика/Бизнес-аналитика',
    'xml': 'Аналитика/Системная аналитика, Аналитика/Дата аналитика',
    'json': 'Аналитика/Системная аналитика, Аналитика/Дата аналитика',
    'soap': 'Аналитика/Системная аналитика',
    'grafana': 'Аналитика/Дата аналитика',
    'graphql': 'Аналитика/Дата аналитика',
    'yandex-datalens': 'Аналитика/Дата аналитика',
    'apache-superset': 'Аналитика/Дата аналитика',
    'elk': 'Аналитика/Дата аналитика',
    'zabbix': 'Аналитика/Дата аналитика',
    'victoriametrics': 'Аналитика/Дата аналитика',
    'influxdb': 'Аналитика/Дата аналитика',
    'elasticsearch': 'Аналитика/Дата аналитика',
    'logstash': 'Аналитика/Дата аналитика',
    'kibana': 'Аналитика/Дата аналитика',
    'pandas': 'ML/DS, Аналитика/Дата аналитика',
    'numpy': 'ML/DS, Аналитика/Дата аналитика',
    'scipy': 'ML/DS',
    'scikit-learn': 'ML/DS',
    'tensorflow': 'ML/DS',
    'pytorch': 'ML/DS',
    'hadoop': 'ML/DS, Разработка/Backend',
    'spark': 'ML/DS',
    'seaborn': 'ML/DS',
    'nlp': 'ML/DS',
    'cv': 'ML/DS',
    'dl': 'ML/DS',
    'nemo': 'ML/DS',
    'transformers': 'ML/DS',
    'pyspark': 'ML/DS',
    'opencv': 'ML/DS',
    'machinelearning': 'ML/DS',
    'triton': 'ML/DS',
    'onnx': 'ML/DS',
    'tensorrt': 'ML/DS',
    'ml': 'ML/DS',
    'sota': 'ML/DS',
    'pymorphy': 'ML/DS',
    'spacy': 'ML/DS',
    'nvidea': 'ML/DS',
    'nltk': 'ML/DS',
    'product': 'Product Management/Product, Product Management/Product, Product Management/Product',
    'product-management': 'Project  Management/Project, Project  Management/Project, Project  Management/Project',
    'project': 'Project  Management/Project, Project  Management/Project, Project  Management/Project',
    'project-management': 'Project  Management/Project, Project  Management/Project, Project  Management/Project',
    'руководитель': 'Project  Management/Project , Project  Management/Project , Project  Management/Project',
}
