from .avito_parser import AvitoParser
from .careerspace_parser import CareerspaceParser
from .changellenge_parser import ChangellengeParser
from .mts_parser import MtsParser
from .sberdev_parser import SberDevParser
from .vseti_parser import VsetiParser
from .aich_parser import AichParser
from .choici_parser import ChoiciParser
from .remocate_parser import RemocateParser
from .superjob_parser import SuperJobParser
from .twogis_parser import TwoGisParser
from .croc_parser import CrocParser
